### PR TITLE
add ERD file

### PR DESCRIPTION
**Pull request by Gracetemitope**
I created an Entity Relational Database in this branch demonstrating the different relationship between various tables (Users, Post, Friendship Request, Likes and Comments).

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, there @Gracetemitope 👋🏾 a great job so far on this milestone. Your first submission is a strong one 😄 However let's make it better by doing the following ⬇️ 

- [x] Rename `Friendship(users)` to only `Users`  lets keep the naming simple 😄 
- [x] Rename `Friendship Request (invitation)` to just ` Friendship` we want to keep our database names easy to remember
- [x] The `User` entity should have an `image_link` column. In your case, you have named it `profile_img`. Kindly rename it
- [x] The `Friendship` entity should have two foreign keys which are `user_id` and `friend_id` and also a column of `status`. Name and email are not relevant for now
- [x] `Friendship` and` User` entities should have multiple relationships
-Currently, your ERD shows a single one-to-many relationship between User and Friendship. The User and Friendship entities have multiple relationships. A User can send many invites and a User can also receive many invites. Also, a sent invitation and a received invitation will always belong to one User. This means that the two foreign keys in the Friendship table pointing to the User table as both senders and receivers are ultimately users.
- [x] In the `Comment` and `Like` entity. kindly add primary keys of `id`
- [x] Show the relationship between the ` User` entity and the `Like` entity.  A user can have one or many likes and this should be reflected in your diagram
- [x] Show the relationship between the ` User` entity and the `Comment` entity.  A user can write one or many comments and this should be reflected in your diagram
- [x] Kindly show clearly the relationship between `Post`, `Comment`, and `Like` entities. For each relationship, draw separate lines for representation
- [x] In the `Likes` entity you have  a typo of `FOK`, Kindly change it to `FK`

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
_If you have any questions, kindly leave a comment here and tag my name @mimipeshy and I will be glad to help_

**Comment by Gracetemitope** [comment]
Hi! Thanks for your review. However, please kindly check the cardinality very well again as I think you're interpreting it wrongly. Every other necessary change has been made Thanks.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Gracetemitope 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] Please change the primary keys to `ID`. (As the previous code reviewer suggested: In the `Comment` and `Like` entity. kindly add primary keys of `id`)
- [x] Please rename the entities to singular as the previous reviewer use the entity's name as singular in her review.

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Gracetemitope** [comment]
Hi! Thanks for your comment. Can you expatiate on the first specified change cos I thought I already did that. Do you mean PK comment_id and like_id.

@umairarshadbutt

**Comment by umairarshadbutt** [comment]
Hi @Gracetemitope 
Yes use the ID instead of comment_id and like_id when they are primary keys

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: :+1: 

**You've painstakingly implemented the required changes from the previous reviews.** 
**Thank you** :+1: :clap: 

**This milestone is approved.** 

[OPTIONAL]
Your GitHub Action linters are not being triggered properly. This would become more important in the coming milestones. Please follow the steps below:

- [ ] Enable the GitHub Actions in the Actions tab.
- [ ] Create the feature/branch and push.
- [ ] Start working on the milestone as usual.
- [ ] Open a PR from the feature/branch when the work is done.

**You may go ahead and merge this branch.**

**Cheers and happy coding.** :+1:

**Pull request merged**
