### PR TITLE
Feature/milestone2

### PR DESCRIPTION
**Pull request by Gracetemitope**
In this milestone, I added the necessary relationship needed for the project in my model. They include, belongs_to, has_many, inverse, e.t.c as required

Unit tests were also carried out to test all these as required

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUESTED  ♻️**

Hi @Gracetemitope, Great Job for working on this milestone project, however for this project to be approved few changes is required: 

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Kindly add more Unit and Integration tests! ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------
Hello @Gracetemitope  Great job you are doing in this milestone :clap: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench: see them below :eyes: :point_down: 
-------------

- [ ] I can see the post from users that are not my friends. Please fix this, I only can see post made for the user and from friends. 
friends_timeline (1)

- [ ] I got this message when I try to send a friend request. 

Screenshot from 2021-05-25 11-06-54

Please fix this because I cannot accept or reject a friend request because I cannot send the request.  

----------------
Make these required changes and send it again for another review :muscle: 
HAPPY CODING!!!

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------
Hello again :wave: great job working on the required changes :muscle: 
However, there is one thing to fix to complete this milestone :wrench: 
--------------

- [ ] If a reject a friendship it creates the friendship. Please fix this. 
----------
Make this change and send it again for another review :+1: :100: 
HAPPY CODING!!!

**Review by carlos-ssh — APPROVED** [review]
# STATUS: APPROVED ✔✔
## Hello 🙋🏽‍♂️ [@Gracetemitope ](https://github.com/Gracetemitope). <br>
## I'm really impressed with your job!!  👨🏽‍💻

**You can merge👍** <br>
**Prepare a Cup of Coffee ☕️☕️☕️** <br>
**And Keep working very hard**

*Happy coding💻💻💻*

**[@Carlos-SSH](https://github.com/carlos-ssh)**

**Pull request merged**
